# Generated by Django 4.2.12 on 2024-05-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safe_bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date_open",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]