# Generated by Django 4.2.12 on 2024-05-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_bank', '0002_account_balance_account_routing_no'),
        ('safe_bank', '0002_alter_account_date_open'),
    ]

    operations = [
    ]
