# Generated by Django 4.2.12 on 2024-05-08 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_bank', '0003_merge_20240508_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_bank.customer'),
        ),
    ]
