# Generated by Django 5.0.6 on 2024-05-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_bank', '0004_alter_account_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
    ]
